version: '2.0'

services:
  db:
    image: mysql:5.7
    container_name: mysql-workforce
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee
      MYSQL_USER: workforce
      MYSQL_PASSWORD: workforce

  workforce:
    depends_on:
    - db
    image: workforce:latest
    ports:
    - "8080:8080"
    restart: always
    volumes:
      - /tmp/workforce/logs:/tmp/workforce/logs
    environment:
      DB_HOST: db
      DB_USERNAME: workforce
      DB_PASSWORD: workforce

volumes:
  db_data: